// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/health_checks_controller.ts').default['handle'], false>
}
type ApiAuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['registerValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['register'], true>
}
type ApiAuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], true>
}
type ApiAuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type ApiAuthMeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['me'], false>
}
type ApiAuthChangepasswordPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['changePasswordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['changePassword'], true>
}
type ApiGamesGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/common.ts')['gameFiltersValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['index'], true>
}
type ApiGamesPopularGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/common.ts')['limitValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['popular'], true>
}
type ApiGamesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['show'], false>
}
type ApiYoutubevideosGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/youtube_videos_controller.ts').default['index'], false>
}
type ApiYoutubevideosActiveGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/common.ts')['limitValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/youtube_videos_controller.ts').default['active'], true>
}
type ApiYoutubevideosIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/youtube_video.ts')['youtubeVideoParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/youtube_videos_controller.ts').default['show'], true>
}
type ApiGenresGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/genres_controller.ts').default['index'], false>
}
type ApiGenresIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/genre.ts')['genreParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/genres_controller.ts').default['show'], true>
}
type ApiPlatformsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/platforms_controller.ts').default['index'], false>
}
type ApiPlatformsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/platform.ts')['platformParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/platforms_controller.ts').default['show'], true>
}
type ApiTagsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/tags_controller.ts').default['index'], false>
}
type ApiTagsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/tag.ts')['tagParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/tags_controller.ts').default['show'], true>
}
type ApiDifficultylevelsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/difficulty_levels_controller.ts').default['index'], false>
}
type ApiDifficultylevelsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/difficulty_level.ts')['difficultyLevelParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/difficulty_levels_controller.ts').default['show'], true>
}
type ApiSeokeywordsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/seo_keywords_controller.ts').default['index'], false>
}
type ApiSeokeywordsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/seo_keyword.ts')['seoKeywordParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/seo_keywords_controller.ts').default['show'], true>
}
type ApiGuidetypesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/guide_types_controller.ts').default['index'], false>
}
type ApiGuidetypesIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_type.ts')['guideTypeParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_types_controller.ts').default['show'], true>
}
type ApiGuidesGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide.ts')['guideFiltersValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['index'], true>
}
type ApiGuidesPopularGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide.ts')['guideFiltersValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['popular'], true>
}
type ApiGuidesSlugIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide.ts')['guideSlugParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['showBySlug'], true>
}
type ApiGuidesGameIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['byGame'], false>
}
type ApiGuidesIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide.ts')['guideParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['show'], true>
}
type ApiArticlecategoriesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/article_categories_controller.ts').default['index'], false>
}
type ApiArticlecategoriesIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article_category.ts')['articleCategoryParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/article_categories_controller.ts').default['show'], true>
}
type ApiArticlesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/articles_controller.ts').default['index'], false>
}
type ApiArticlesPopularGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/articles_controller.ts').default['popular'], false>
}
type ApiArticlesSlugIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article.ts')['articleSlugValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/articles_controller.ts').default['showBySlug'], true>
}
type ApiArticlesIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article.ts')['articleParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/articles_controller.ts').default['show'], true>
}
type ApiMaintenanceStatusGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/maintenance_settings_controller.ts').default['status'], false>
}
type ApiAdminGamesStatsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['stats'], false>
}
type ApiAdminGamesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['show'], false>
}
type ApiAdminGamesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/game.ts')['createGameValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['store'], true>
}
type ApiAdminGamesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/game.ts')['updateGameValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['update'], true>
}
type ApiAdminGamesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/game.ts')['gameParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/games_controller.ts').default['destroy'], true>
}
type ApiAdminYoutubevideosPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/youtube_video.ts')['createYoutubeVideoValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/youtube_videos_controller.ts').default['store'], true>
}
type ApiAdminYoutubevideosIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/youtube_video.ts')['updateYoutubeVideoValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/youtube_videos_controller.ts').default['update'], true>
}
type ApiAdminYoutubevideosIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/youtube_video.ts')['youtubeVideoParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/youtube_videos_controller.ts').default['destroy'], true>
}
type ApiAdminGenresPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/genre.ts')['createGenreValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/genres_controller.ts').default['store'], true>
}
type ApiAdminGenresIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/genre.ts')['updateGenreValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/genres_controller.ts').default['update'], true>
}
type ApiAdminGenresIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/genre.ts')['genreParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/genres_controller.ts').default['destroy'], true>
}
type ApiAdminPlatformsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/platform.ts')['createPlatformValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/platforms_controller.ts').default['store'], true>
}
type ApiAdminPlatformsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/platform.ts')['updatePlatformValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/platforms_controller.ts').default['update'], true>
}
type ApiAdminPlatformsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/platform.ts')['platformParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/platforms_controller.ts').default['destroy'], true>
}
type ApiAdminTagsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/tag.ts')['createTagValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/tags_controller.ts').default['store'], true>
}
type ApiAdminTagsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/tag.ts')['updateTagValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/tags_controller.ts').default['update'], true>
}
type ApiAdminTagsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/tag.ts')['tagParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/tags_controller.ts').default['destroy'], true>
}
type ApiAdminDifficultylevelsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/difficulty_level.ts')['createDifficultyLevelValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/difficulty_levels_controller.ts').default['store'], true>
}
type ApiAdminDifficultylevelsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/difficulty_level.ts')['updateDifficultyLevelValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/difficulty_levels_controller.ts').default['update'], true>
}
type ApiAdminDifficultylevelsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/difficulty_level.ts')['difficultyLevelParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/difficulty_levels_controller.ts').default['destroy'], true>
}
type ApiAdminSeokeywordsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/seo_keyword.ts')['createSeoKeywordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/seo_keywords_controller.ts').default['store'], true>
}
type ApiAdminSeokeywordsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/seo_keyword.ts')['updateSeoKeywordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/seo_keywords_controller.ts').default['update'], true>
}
type ApiAdminSeokeywordsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/seo_keyword.ts')['seoKeywordParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/seo_keywords_controller.ts').default['destroy'], true>
}
type ApiAdminGuidetypesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_type.ts')['createGuideTypeValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_types_controller.ts').default['store'], true>
}
type ApiAdminGuidetypesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_type.ts')['updateGuideTypeValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_types_controller.ts').default['update'], true>
}
type ApiAdminGuidetypesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_type.ts')['guideTypeParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_types_controller.ts').default['destroy'], true>
}
type ApiAdminGuidesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide.ts')['createGuideValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['store'], true>
}
type ApiAdminGuidesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide.ts')['updateGuideValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['update'], true>
}
type ApiAdminGuidesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide.ts')['guideParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guides_controller.ts').default['destroy'], true>
}
type ApiAdminGuidesIdSectionsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/guide_sections_controller.ts').default['index'], false>
}
type ApiAdminGuidesIdSectionsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_section.ts')['createGuideSectionValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_sections_controller.ts').default['store'], true>
}
type ApiAdminGuidesSectionsIdGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_section.ts')['guideSectionParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_sections_controller.ts').default['show'], true>
}
type ApiAdminGuidesSectionsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_section.ts')['updateGuideSectionValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_sections_controller.ts').default['update'], true>
}
type ApiAdminGuidesSectionsIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/guide_section.ts')['guideSectionParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/guide_sections_controller.ts').default['destroy'], true>
}
type ApiAdminArticlecategoriesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article_category.ts')['createArticleCategoryValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/article_categories_controller.ts').default['store'], true>
}
type ApiAdminArticlecategoriesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article_category.ts')['updateArticleCategoryValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/article_categories_controller.ts').default['update'], true>
}
type ApiAdminArticlecategoriesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article_category.ts')['articleCategoryParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/article_categories_controller.ts').default['destroy'], true>
}
type ApiAdminArticlesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article.ts')['createArticleValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/articles_controller.ts').default['store'], true>
}
type ApiAdminArticlesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article.ts')['updateArticleValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/articles_controller.ts').default['update'], true>
}
type ApiAdminArticlesIdDelete = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/article.ts')['articleParamsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/articles_controller.ts').default['destroy'], true>
}
type ApiAdminArticlesIdImagesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/article_images_controller.ts').default['index'], false>
}
type ApiAdminArticlesIdImagesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/article_images_controller.ts').default['store'], false>
}
type ApiAdminArticlesIdImagesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/article_images_controller.ts').default['destroy'], false>
}
type ApiAdminImagesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/images_controller.ts').default['show'], false>
}
type ApiAdminImagesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/images_controller.ts').default['destroy'], false>
}
type ApiAdminMaintenancePut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/maintenance_setting.ts')['updateMaintenanceSettingValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/maintenance_settings_controller.ts').default['update'], true>
}
type ApiAdminMaintenanceEnablePatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/maintenance_setting.ts')['enableMaintenanceValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/maintenance_settings_controller.ts').default['enable'], true>
}
type ApiAdminMaintenanceDisablePatch = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/maintenance_settings_controller.ts').default['disable'], false>
}
export interface ApiDefinition {
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
  'api': {
    'auth': {
      'register': {
        '$url': {
        };
        '$post': ApiAuthRegisterPost;
      };
      'login': {
        '$url': {
        };
        '$post': ApiAuthLoginPost;
      };
      'logout': {
        '$url': {
        };
        '$post': ApiAuthLogoutPost;
      };
      'me': {
        '$url': {
        };
        '$get': ApiAuthMeGetHead;
        '$head': ApiAuthMeGetHead;
      };
      'change-password': {
        '$url': {
        };
        '$post': ApiAuthChangepasswordPost;
      };
    };
    'games': {
      '$url': {
      };
      '$get': ApiGamesGetHead;
      '$head': ApiGamesGetHead;
      'popular': {
        '$url': {
        };
        '$get': ApiGamesPopularGetHead;
        '$head': ApiGamesPopularGetHead;
      };
      ':slug': {
        '$url': {
        };
        '$get': ApiGamesIdGetHead;
        '$head': ApiGamesIdGetHead;
      };
    };
    'youtube-videos': {
      '$url': {
      };
      '$get': ApiYoutubevideosGetHead;
      '$head': ApiYoutubevideosGetHead;
      'active': {
        '$url': {
        };
        '$get': ApiYoutubevideosActiveGetHead;
        '$head': ApiYoutubevideosActiveGetHead;
      };
      ':id': {
        '$url': {
        };
        '$get': ApiYoutubevideosIdGetHead;
        '$head': ApiYoutubevideosIdGetHead;
      };
    };
    'genres': {
      '$url': {
      };
      '$get': ApiGenresGetHead;
      '$head': ApiGenresGetHead;
      ':id': {
        '$url': {
        };
        '$get': ApiGenresIdGetHead;
        '$head': ApiGenresIdGetHead;
      };
    };
    'platforms': {
      '$url': {
      };
      '$get': ApiPlatformsGetHead;
      '$head': ApiPlatformsGetHead;
      ':id': {
        '$url': {
        };
        '$get': ApiPlatformsIdGetHead;
        '$head': ApiPlatformsIdGetHead;
      };
    };
    'tags': {
      '$url': {
      };
      '$get': ApiTagsGetHead;
      '$head': ApiTagsGetHead;
      ':id': {
        '$url': {
        };
        '$get': ApiTagsIdGetHead;
        '$head': ApiTagsIdGetHead;
      };
    };
    'difficulty-levels': {
      '$url': {
      };
      '$get': ApiDifficultylevelsGetHead;
      '$head': ApiDifficultylevelsGetHead;
      ':id': {
        '$url': {
        };
        '$get': ApiDifficultylevelsIdGetHead;
        '$head': ApiDifficultylevelsIdGetHead;
      };
    };
    'seo-keywords': {
      '$url': {
      };
      '$get': ApiSeokeywordsGetHead;
      '$head': ApiSeokeywordsGetHead;
      ':id': {
        '$url': {
        };
        '$get': ApiSeokeywordsIdGetHead;
        '$head': ApiSeokeywordsIdGetHead;
      };
    };
    'guide-types': {
      '$url': {
      };
      '$get': ApiGuidetypesGetHead;
      '$head': ApiGuidetypesGetHead;
      ':id': {
        '$url': {
        };
        '$get': ApiGuidetypesIdGetHead;
        '$head': ApiGuidetypesIdGetHead;
      };
    };
    'guides': {
      '$url': {
      };
      '$get': ApiGuidesGetHead;
      '$head': ApiGuidesGetHead;
      'popular': {
        '$url': {
        };
        '$get': ApiGuidesPopularGetHead;
        '$head': ApiGuidesPopularGetHead;
      };
      'slug': {
        ':slug': {
          '$url': {
          };
          '$get': ApiGuidesSlugIdGetHead;
          '$head': ApiGuidesSlugIdGetHead;
        };
      };
      'game': {
        ':gameId': {
          '$url': {
          };
          '$get': ApiGuidesGameIdGetHead;
          '$head': ApiGuidesGameIdGetHead;
        };
      };
      ':id': {
        '$url': {
        };
        '$get': ApiGuidesIdGetHead;
        '$head': ApiGuidesIdGetHead;
      };
    };
    'article-categories': {
      '$url': {
      };
      '$get': ApiArticlecategoriesGetHead;
      '$head': ApiArticlecategoriesGetHead;
      ':id': {
        '$url': {
        };
        '$get': ApiArticlecategoriesIdGetHead;
        '$head': ApiArticlecategoriesIdGetHead;
      };
    };
    'articles': {
      '$url': {
      };
      '$get': ApiArticlesGetHead;
      '$head': ApiArticlesGetHead;
      'popular': {
        '$url': {
        };
        '$get': ApiArticlesPopularGetHead;
        '$head': ApiArticlesPopularGetHead;
      };
      'slug': {
        ':slug': {
          '$url': {
          };
          '$get': ApiArticlesSlugIdGetHead;
          '$head': ApiArticlesSlugIdGetHead;
        };
      };
      ':id': {
        '$url': {
        };
        '$get': ApiArticlesIdGetHead;
        '$head': ApiArticlesIdGetHead;
      };
    };
    'maintenance': {
      'status': {
        '$url': {
        };
        '$get': ApiMaintenanceStatusGetHead;
        '$head': ApiMaintenanceStatusGetHead;
      };
    };
    'admin': {
      'games': {
        'stats': {
          '$url': {
          };
          '$get': ApiAdminGamesStatsGetHead;
          '$head': ApiAdminGamesStatsGetHead;
        };
        ':id': {
          '$url': {
          };
          '$get': ApiAdminGamesIdGetHead;
          '$head': ApiAdminGamesIdGetHead;
          '$put': ApiAdminGamesIdPut;
          '$delete': ApiAdminGamesIdDelete;
        };
        '$url': {
        };
        '$post': ApiAdminGamesPost;
      };
      'youtube-videos': {
        '$url': {
        };
        '$post': ApiAdminYoutubevideosPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminYoutubevideosIdPut;
          '$delete': ApiAdminYoutubevideosIdDelete;
        };
      };
      'genres': {
        '$url': {
        };
        '$post': ApiAdminGenresPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminGenresIdPut;
          '$delete': ApiAdminGenresIdDelete;
        };
      };
      'platforms': {
        '$url': {
        };
        '$post': ApiAdminPlatformsPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminPlatformsIdPut;
          '$delete': ApiAdminPlatformsIdDelete;
        };
      };
      'tags': {
        '$url': {
        };
        '$post': ApiAdminTagsPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminTagsIdPut;
          '$delete': ApiAdminTagsIdDelete;
        };
      };
      'difficulty-levels': {
        '$url': {
        };
        '$post': ApiAdminDifficultylevelsPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminDifficultylevelsIdPut;
          '$delete': ApiAdminDifficultylevelsIdDelete;
        };
      };
      'seo-keywords': {
        '$url': {
        };
        '$post': ApiAdminSeokeywordsPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminSeokeywordsIdPut;
          '$delete': ApiAdminSeokeywordsIdDelete;
        };
      };
      'guide-types': {
        '$url': {
        };
        '$post': ApiAdminGuidetypesPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminGuidetypesIdPut;
          '$delete': ApiAdminGuidetypesIdDelete;
        };
      };
      'guides': {
        '$url': {
        };
        '$post': ApiAdminGuidesPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminGuidesIdPut;
          '$delete': ApiAdminGuidesIdDelete;
        };
        ':guideId': {
          'sections': {
            '$url': {
            };
            '$get': ApiAdminGuidesIdSectionsGetHead;
            '$head': ApiAdminGuidesIdSectionsGetHead;
            '$post': ApiAdminGuidesIdSectionsPost;
          };
        };
        'sections': {
          ':id': {
            '$url': {
            };
            '$get': ApiAdminGuidesSectionsIdGetHead;
            '$head': ApiAdminGuidesSectionsIdGetHead;
            '$put': ApiAdminGuidesSectionsIdPut;
            '$delete': ApiAdminGuidesSectionsIdDelete;
          };
        };
      };
      'article-categories': {
        '$url': {
        };
        '$post': ApiAdminArticlecategoriesPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminArticlecategoriesIdPut;
          '$delete': ApiAdminArticlecategoriesIdDelete;
        };
      };
      'articles': {
        '$url': {
        };
        '$post': ApiAdminArticlesPost;
        ':id': {
          '$url': {
          };
          '$put': ApiAdminArticlesIdPut;
          '$delete': ApiAdminArticlesIdDelete;
        };
        ':articleId': {
          'images': {
            '$url': {
            };
            '$get': ApiAdminArticlesIdImagesGetHead;
            '$head': ApiAdminArticlesIdImagesGetHead;
            '$post': ApiAdminArticlesIdImagesPost;
            ':imageId': {
              '$url': {
              };
              '$delete': ApiAdminArticlesIdImagesIdDelete;
            };
          };
        };
      };
      'images': {
        ':id': {
          '$url': {
          };
          '$get': ApiAdminImagesIdGetHead;
          '$head': ApiAdminImagesIdGetHead;
          '$delete': ApiAdminImagesIdDelete;
        };
      };
      'maintenance': {
        '$url': {
        };
        '$put': ApiAdminMaintenancePut;
        'enable': {
          '$url': {
          };
          '$patch': ApiAdminMaintenanceEnablePatch;
        };
        'disable': {
          '$url': {
          };
          '$patch': ApiAdminMaintenanceDisablePatch;
        };
      };
    };
  };
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/uploads/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
